### ISSUE TITLE
pod install error

### ISSUE THREAD

**Issue by xiaoheiai4719** [AXErunners/axesync#1]
hi  RuntimeError - [!] Xcodeproj doesn't know about the following attributes {"inputFileListPaths"=>[], "outputFileListPaths"=>[]} for the 'PBXShellScriptBuildPhase' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new

**Comment by charlesrocket** [comment]
fixed with module update
